### ISSUE TITLE
USER STORY: Access ongoing equality and diversity info

### ISSUE THREAD

**Issue by JohnWGardner** [JohnWGardner/Equality_and_Diversity#18]
# Story

As detailed here, for this project: #1

- As a **role** I can **capability** so that **received benefit**:

- [ ] _As a_ **customer** _I can_ **access ongoing and up to date equality information** _so that_ **I can enable good practice in the  workplace**

- In order to **receive benefit** as a **role**, I can **goal / desire**:

- [ ] _In order to_ **ensure good equality practice** _as a_ **director**, _I can_ **access ongoing and up to date equality information**

# *Acceptance Criteria*

- [ ]  Acceptance Criteria 1: _I know when I am done when:_ **I have a way of registering my interest for receiving proactive, ongoing updates happening in the equality landscape**

- [ ]  Acceptance Criteria 2: _I know when I am done when:_ **I have a way of searching in real time on social media in a focused area for ongoing updates happening in the equality landscape**

- [ ]  Acceptance Criteria 3: NA

# Tasks:

- [ ] Task 1
- [x] Task 2
- [ ] Task 3

***
