### ISSUE TITLE
USER STORY: another user story

### ISSUE THREAD

**Issue by JohnWGardner** [JohnWGardner/Equality_and_Diversity#19]
# Story

_As a_ **customer** _I can_ **add multiple equality information sheets to a cart** _so that_ **I can manage muliple items at the same time**

- [ ] _In order to_ **make best use of my time** _as a_ **customer**, _I can_ **access multiple equality information sheets at the same time**

# *Acceptance Criteria*

- [ ]  Acceptance Criteria 1: _I know when I am done when:_ **I can sort multiple equality information sheets into a container**

- [ ]  Acceptance Criteria 2: _I know when I am done when:_ **I have access multiple equality information sheets at the same time**

- [ ]  Acceptance Criteria 3: NA

# Tasks:

- [ ] Task 1
- [x] Task 2
- [ ] Task 3

***

**Comment by JohnWGardner** [comment]
This completed

**Comment by JohnWGardner** [comment]
Reopen issue
